- name: "Checking VMWare WS instalation..."
  stat:
    path: /usr/bin/vmware
  register: vmware_check

- name: "Uninstalling"
  command: "sh vmware-installer -u vmware-workstation --required"
  when: vmware_check.stat.exists
  failed_when: false
  notify: reboot

- name: "Updating kernel module status"
  command:
    cmd: "depmod -a"
  changed_when: false
